remove header propagation implementations
Valensas/spring-kafka pull request #10
Opened 2024-08-13 12:04 UTC by yavuzselimkaraman

remove kafka and web header implementations @moray95 @cantaylancapraz

2024-08-13 12:27 UTC, moray95 requested changes

2024-08-13 12:27 UTC, moray95 commented on build.gradle.kts
>      compileOnly("org.springframework.boot:spring-boot-starter-web")
Bunları kaldırabiliriz sanırım

2024-08-13 12:36 UTC, yavuzselimkaraman commented on build.gradle.kts
>      compileOnly("org.springframework.boot:spring-boot-starter-web")
doğru. kaldırdım.

2024-08-13 14:28 UTC, moray95 approved these changes

2024-08-14 10:35 UTC, ayseozbekk approved these changes

2024-08-14 12:08 UTC, taylancapraz approved these changes

2024-08-14 12:15 UTC, merged